site_name: Dialectal Swiss German NLP Resources
theme:
  name: material

nav:
  - Home: index.md
  - Datasets:
      - Text corpora: datasets/text-corpora.md
      - Speech corpora: datasets/speech-corpora.md
  - Tasks:
      - Automatic Speech Recognition: tasks/asr.md
      - Machine Translation / Normalization: tasks/mt.md
      - Miscellaneous: tasks/misc.md